
import { Flashcard } from '../types';
import * as srs from '../services/srsService';

const today = srs.todayISO();

export const SAMPLE_FLASHCARDS: Omit<Flashcard, 'id'>[] = [
  {
    createdAt: today,
    updatedAt: today,
    discipline: "Scrum / Agile",
    topic: "Pilares do Scrum",
    front: "Quais são os três pilares do empirismo no Scrum?",
    back: "Transparência, Inspeção e Adaptação.",
    comments: "Estes são os pilares do empirismo, que é a base do Scrum. Transparência permite a Inspeção, que por sua vez possibilita a Adaptação.",
    type: "basic",
    tags: ["scrum-guide", "conceito"],
    stability: 12,
    lastReviewedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    nextReviewDate: new Date(Date.now() + 5 * 86400000).toISOString(),
    masteryScore: 85,
    recentError: 0,
    hotTopic: true,
    isCritical: false,
    isFundamental: false,
    totalAttempts: 3,
    lastWasCorrect: true,
    correctStreak: 2,
    srsStage: 2,
    lastAttemptDate: new Date(Date.now() - 3 * 86400000).toISOString().split('T')[0],
    attemptHistory: [],
    masteryHistory: [],
    pairMatchPlayed: false,
    timeSec: 0,
    selfEvalLevel: 0
  },
  {
    createdAt: today,
    updatedAt: today,
    discipline: "Scrum / Agile",
    topic: "Artefatos Scrum",
    front: "Quem é o único responsável por gerenciar o Product Backlog?",
    back: "O Product Owner.",
    comments: "Lembre-se: Ninguém mais pode mandar a equipe de desenvolvimento fazer algo de uma lista diferente.",
    type: "basic",
    tags: ["responsabilidade", "po"],
    stability: 4,
    lastReviewedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    nextReviewDate: new Date(Date.now() - 1 * 86400000).toISOString(),
    masteryScore: 35,
    recentError: 1,
    hotTopic: true,
    isCritical: true,
    isFundamental: false,
    totalAttempts: 5,
    lastWasCorrect: false,
    correctStreak: 0,
    srsStage: 0,
    lastAttemptDate: new Date(Date.now() - 1 * 86400000).toISOString().split('T')[0],
    attemptHistory: [],
    masteryHistory: [],
    pairMatchPlayed: false,
    timeSec: 0,
    selfEvalLevel: 0
  },
  {
    createdAt: today,
    updatedAt: today,
    discipline: "Direito Tributário",
    topic: "Exclusão do Crédito",
    front: "A {{c1::isenção}} e a {{c2::anistia}} são formas de exclusão do crédito tributário.",
    back: "Correto. Ambas impedem a constituição definitiva do crédito tributário.",
    comments: "",
    type: "cloze",
    tags: ["ctn", "literalidade"],
    stability: 30,
    lastReviewedAt: new Date(Date.now() - 15 * 86400000).toISOString(),
    nextReviewDate: new Date(Date.now() + 10 * 86400000).toISOString(),
    masteryScore: 95,
    recentError: 0,
    hotTopic: false,
    isCritical: false,
    isFundamental: false,
    totalAttempts: 4,
    lastWasCorrect: true,
    correctStreak: 4,
    srsStage: 4,
    lastAttemptDate: new Date(Date.now() - 15 * 86400000).toISOString().split('T')[0],
    attemptHistory: [],
    masteryHistory: [],
    pairMatchPlayed: false,
    timeSec: 0,
    selfEvalLevel: 0
  },
  {
    createdAt: today,
    updatedAt: today,
    discipline: "Scrum / Agile",
    topic: "Eventos Scrum",
    front: "Qual o time-box máximo para uma Sprint de um mês?",
    back: "A própria Sprint tem um time-box de um mês. A Sprint Planning para essa Sprint teria um time-box máximo de 8 horas.",
    comments: "",
    type: "basic",
    tags: ["time-box"],
    stability: 1,
    totalAttempts: 0,
    lastWasCorrect: false,
    masteryScore: 0,
    nextReviewDate: today,
    hotTopic: false,
    isCritical: false,
    isFundamental: false,
    correctStreak: 0,
    srsStage: 0,
    lastAttemptDate: '',
    attemptHistory: [],
    masteryHistory: [],
    recentError: 0,
    pairMatchPlayed: false,
    timeSec: 0,
    selfEvalLevel: 0
  }
];
